# server
server.port=8081


spring.datasource.url=jdbc:h2:file:./data/touristdb;DB_CLOSE_ON_EXIT=FALSE
# use a fixed in-memory DB name so the H2 console can connect
#spring.datasource.url=jdbc:h2:mem:touristdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# let Hibernate auto-create tables for dev
spring.jpa.hibernate.ddl-auto=update

# enable the H2 console (embedded in the same JVM)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


